
texture:
  title: Dr Matthew Vaughan
  tagline: Physicist. Electronic Hobbyist
  date_format: "%b %-d, %Y"

  social_links:
    #twitter: thelehhman
    github:  HalfHeuslerAlloy
    linkedIn: in/matthew-vaughan-49231919b/ # format: locale/username

  style: [purple]

  showPicker: false

  showNav: true

  navigation:
   - title: Home
     url: "/"
   - title: About
     url: "/about"



# Build settings
#theme: texture
remote_theme: samarsault/texture
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-remote-theme