texture:
  title: Dr Matthew Vaughan
  tagline: Physicist. Hacker
  date_format: "%b %-d, %Y"

  social_links:
    #twitter: thelehhman
    github:  HalfHeuslerAlloy
    #linkedIn: in/thelehhman # format: locale/username
  
  style: [purple]
  
  showPicker: false
  
  showNav: true
  
  navigation:
   - title: Home
     url: "/"
   - title: About
     url: "/about"

# Build settings
theme: texture
remote_theme: samarsault/texture
plugins:
  - jekyll-feed