texture:
  title: Dr Matthew Vaughan
  tagline: Physicist. Hacker
  date_format: "%b %-d, %Y"

  social_links:
    #twitter: thelehhman
    github:  HalfHeuslerAlloy
    #linkedIn: in/thelehhman # format: locale/username
  
  style: [purple]
  
  showPicker: false
  
  showNav: true

# Build settings
theme: texture
plugins:
  - jekyll-feed